# Generated by Django 4.1.1 on 2022-11-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='personal_id',
            new_name='candidate_id',
        ),
    ]
