# Generated by Django 4.1.1 on 2022-10-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='vying_position',
        ),
    ]
