# Generated by Django 4.1.1 on 2022-10-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
